services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:latest
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      # - KAFKA_LISTENERS=PLAINTEXT://:9092
      # - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  console:
    image: redpandadata/console:latest
    ports:
      - 8080:8080
    links:
      - kafka
    environment:
      - KAFKA_BROKERS=kafka:9092
  mysql:
    image: mysql:8.0.38
    ports:
      - 3306:3306
    volumes:
       - "./sql:/docker-entrypoint-initdb.d"
    environment:
      - MYSQL_ROOT_PASSWORD=debezium
  connect:
    image: mydebezium
    build:
      context: .
    ports:
      - 8083:8083
      - 5005:5005
    links:
      - kafka
      - mysql
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=debezium.connect_configs
      - OFFSET_STORAGE_TOPIC=debezium.connect_offsets
      - STATUS_STORAGE_TOPIC=debezium.connect_statuses