# hostPort: 127.0.0.1:9095
startDelaySeconds: 0
ssl: false
lowercaseOutputName: false
lowercaseOutputLabelNames: false

whitelistObjectNames:
  - "debezium.mysql:*"
  - "kafka.connect:type=connect-worker-metrics"
  - "kafka.connect:type=connector-metrics,connector=*"
  - "kafka.connect:type=source-task-metrics,connector=*,task=*"
  - "kafka.connect:type=sink-task-metrics,connector=*,task=*"
  # - "kafka.consumer:type=consumer-fetch-manager-metrics,client-id=*"
  # - "kafka.producer:type=producer-metrics,client-id=*"

rules:

- pattern: debezium.([^:]+)<type=connector-metrics, context=([^,]+), server=([^,]+)><>(TotalNumberOfEventsSeen|Connected|NumberOfSkippedEvents)
  name: "debezium.metrics_$4"
  labels:
    plugin: "$1"
    name: "$3"
    context: "$2"
  type: GAUGE

- pattern: "debezium.([^:]+)<type=connector-metrics, context=([^,]+), server=([^,]+), key=([^>]+)><>RowsScanned"
  name: "debezium.metrics_RowsScanned"
  labels:
    plugin: "$1"
    name: "$3"
    context: "$2"
    table: "$4"
  type: GAUGE

# - pattern: "debezium.([^:]+)<type=connector-metrics, server=([^,]+), task=([^,]+), context=([^,]+), database=([^>]+)>([^:]+)"
#   name: "debezium_metrics_$6"
#   labels:
#     plugin: "$1"
#     name: "$2"
#     task: "$3"
#     context: "$4"
#     database: "$5"
#   type: GAUGE

# - pattern: "debezium.([^:]+)<type=connector-metrics, server=([^,]+), task=([^,]+), context=([^>]+)>([^:]+)"
#   name: "debezium_metrics_$5"
#   labels:
#     plugin: "$1"
#     name: "$2"
#     task: "$3"
#     context: "$4"
#   type: GAUGE

# - pattern: "debezium.([^:]+)<type=connector-metrics, context=([^,]+), server=([^>]+)>([^:]+)"
#   name: "debezium_metrics_$4"
#   labels:
#     plugin: "$1"
#     name: "$3"
#     context: "$2"
#   type: GAUGE

# - pattern: 'kafka.(.+)<type=app-info, client-id=(.+)><>start-time-ms'
#   name: kafka_$1_start_time_seconds
#   labels:
#     clientId: "$2"
#   help: "Kafka $1 JMX metric start time seconds"
#   type: GAUGE
#   valueFactor: 0.001 

# - pattern: 'kafka.(.+)<type=app-info, client-id=(.+)><>(commit-id|version): (.+)'
#   name: kafka_$1_$3_info
#   value: 1
#   labels:
#     clientId: "$2"
#     $3: "$4"
#   help: "Kafka $1 JMX metric info version and commit-id"
#   type: GAUGE

# #kafka.producer:type=producer-topic-metrics,client-id="{clientid}",topic="{topic}"", partition="{partition}"
# #kafka.consumer:type=consumer-fetch-manager-metrics,client-id="{clientid}",topic="{topic}"", partition="{partition}"
# - pattern: kafka.(.+)<type=(.+)-metrics, client-id=(.+), topic=(.+), partition=(.+)><>(.+-total|compression-rate|.+-avg|.+-replica|.+-lag|.+-lead)
#   name: kafka_$2-$6
#   labels:
#     clientId: "$3"
#     topic: "$4"
#     partition: "$5"
#   help: "Kafka $1 JMX metric type $2"
#   type: GAUGE

# #kafka.producer:type=producer-topic-metrics,client-id="{clientid}",topic="{topic}"
# #kafka.consumer:type=consumer-fetch-manager-metrics,client-id="{clientid}",topic="{topic}"", partition="{partition}"
# - pattern: kafka.(.+)<type=(.+)-metrics, client-id=(.+), topic=(.+)><>(.+-total|compression-rate|.+-avg)
#   name: kafka_$2-$5
#   labels:
#     clientId: "$3"
#     topic: "$4"
#   help: "Kafka $1 JMX metric type $2"
#   type: GAUGE

# #kafka.connect:type=connect-node-metrics,client-id="{clientid}",node-id="{nodeid}"
# #kafka.consumer:type=consumer-node-metrics,client-id=consumer-1,node-id="{nodeid}"
# - pattern: kafka.(.+)<type=(.+)-metrics, client-id=(.+), node-id=(.+)><>(.+-total|.+-avg)
#   name: kafka_$2-$5
#   labels:
#     clientId: "$3"
#     nodeId: "$4"
#   help: "Kafka $1 JMX metric type $2"
#   type: UNTYPED

# #kafka.connect:type=kafka-metrics-count,client-id="{clientid}"
# #kafka.consumer:type=consumer-fetch-manager-metrics,client-id="{clientid}"
# #kafka.consumer:type=consumer-coordinator-metrics,client-id="{clientid}"
# #kafka.consumer:type=consumer-metrics,client-id="{clientid}"
# #kafka.producer:type=producer-metrics,client-id="{clientId}"
# - pattern: kafka.(.+)<type=(.+)-metrics, client-id=(.*)><>(.+-total|.+-avg|.+-bytes|.+-count|.+-ratio|.+-age|.+-flight|.+-threads|.+-connectors|.+-tasks|.+-ago)
#   name: kafka_$2-$4
#   labels:
#     clientId: "$3"
#   help: "Kafka $1 JMX metric type $2"
#   type: GAUGE

# #kafka.connect:type=connector-metrics,connector="{connector}"<> status"
- pattern: 'kafka.connect<type=connector-metrics, connector=(.+)><>status: ([a-z-]+)'
  name: debezium.kafka_connect_connector_status
  value: 0
  labels:
    connector: "$1"
    status: "$2"
  help: "Kafka Connect JMX Connector status"
  type: GAUGE

#kafka.connect:type=connect-worker-metrics
- pattern: kafka.connect<type=connect-worker-metrics><>(connector-count)
  name: debezium.kafka_connect_connector_count
  help: "Kafka Connect JMX metric connector count"
  type: GAUGE

#kafka.consumer:type=consumer-fetch-manager-metrics,client-id="{clientId}"
# - pattern: kafka.consumer<type=consumer-fetch-manager-metrics, client-id=(.+)><>(records-consumed-rate)
#   name: debezium.kafka_consumer_records_consumed_rate
#   help: "Kafka Connect JMX metric records consumed rate"
#   type: GAUGE

# - pattern: kafka.producer<type=producer-metrics, client-id=(.+)><>(record-send-rate)
#   name: debezium.kafka_producer_record_send_rate
#   help: "Kafka Connect JMX metric records send rate"
#   type: GAUGE

# #kafka.connect:type=task-error-metrics,connector="{connector}",task="{task}"
# #kafka.connect:type=source-task-metrics,connector="{connector}",task="{task}"
# #kafka.connect:type=sink-task-metrics,connector="{connector}",task="{task}"
# #kafka.connect:type=connector-task-metrics,connector="{connector}",task="{task}"
- pattern: kafka.connect<type=(.+)-metrics, connector=(.+), task=(.+)><>(.+-rate)
  name: debezium.kafka_connect_$1_$4_value
  labels:
    connector: "$2"
    task: "$3"
  help: "Kafka Connect JMX metric type $1"
  type: GAUGE

# #kafka.connect:type=connector-metrics,connector="{connector}"
# #kafka.connect:type=connect-worker-metrics,connector="{connector}"
# - pattern: kafka.connect<type=connect-worker-metrics, connector=(.+)><>([a-z-]+)
#   name: kafka_connect_worker_$2
#   labels:
#     connector: "$1"
#   help: "Kafka Connect JMX metric $1"
#   type: GAUGE

# #kafka.connect:type=connect-worker-metrics
# - pattern: kafka.connect<type=connect-worker-metrics><>([a-z-]+)
#   name: kafka_connect_worker_$1
#   help: "Kafka Connect JMX metric worker"
#   type: GAUGE

# #kafka.connect:type=connect-worker-rebalance-metrics
# - pattern: kafka.connect<type=connect-worker-rebalance-metrics><>([a-z-]+)
#   name: kafka_connect_worker_rebalance_$1
#   help: "Kafka Connect JMX metric rebalance information"
#   type: GAUGE
