#!/bin/bash

DEBEZIUM_VERSION=2.6
export DEBEZIUM_ZOOKEEPER_VERSION=${DEBEZIUM_VERSION}
export DEBEZIUM_KAFKA_VERSION=${DEBEZIUM_VERSION}
export DEBEZIUM_CONNECT_VERSION=${DEBEZIUM_VERSION}
# DEBEZIUM_ZOOKEEPER_VERSION=${DEBEZIUM_VERSION}
export MYSQL_VERSION=8.0.38

docker compose -f docker-compose.yml up
